Repository entando-k8s/entando-k8s-composite-app-controller, pull requests merged in 2020-10, with the labels that each got.

#10 ENG-1266 bumped to latest version of all projects
  jenkins-x.yml
  pom.xml
  src/test/java/org/entando/kubernetes/compositeapp/controller/AbstractCompositeAppControllerTest.java
Labels: approved, size/S

#11 Eng 872 bumped dependencies
  .idea/runConfigurations/Tags__in_process__.xml
  charts/preview/templates/operator-role.yaml
  pom.xml
  src/test/java/org/entando/kubernetes/compositeapp/controller/AbstractCompositeAppControllerTest.java
  src/test/java/org/entando/kubernetes/compositeapp/controller/inprocesstests/CompositeAppControllerMockedTest.java
  src/test/java/org/entando/kubernetes/compositeapp/controller/interprocesstests/CompositeAppControllerIntegratedTest.java
Labels: approved, size/M

#12 ENG-1329 bumped to latest operator common
  pom.xml
  src/main/java/org/entando/kubernetes/compositeapp/controller/EntandoCompositeAppController.java
  src/test/java/org/entando/kubernetes/compositeapp/controller/AbstractCompositeAppControllerTest.java
Labels: approved, size/M

#13 Update OWNERS
  OWNERS
Labels: size/XS
